### ISSUE TITLE
lcuda not found

### ISSUE THREAD

**Issue by tjeden** [xman/sgc-ruby-cuda#2]
I have cuda installed in default location. I'm trying to run example from http://blog.speedgocomputing.com/2010/09/cuda-programming-with-ruby.html

After ruby extconf.rb I got:

```
checking for main() in -lcuda... no
creating Makefile
```

I suppose I should change something with my paths?

**Comment by xman** [comment]
The libcuda.so is provided by Nvidia. Suppose installing latest Nvidia driver would have included that in standard lib directory.

In my Fedora 14 installed with Nvidia driver, I have

$ locate cuda.so

/usr/lib/libcuda.so

/usr/lib/libcuda.so.1

/usr/lib/libcuda.so.260.19.12

/usr/lib64/libcuda.so

/usr/lib64/libcuda.so.1

/usr/lib64/libcuda.so.260.19.12

**Comment by regismesquita** [comment]
if you are using a mac the extension will be .dylib , you will need to pass the --with-opt-lib=/usr/local/cuda/lib/ parameter to the extconf
